# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Build docs in all formats
formats: all

# Set the version of Python and build requirements
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc  # This is relevant as it specifies the Sphinx version

# Need to install additional dependencies into the container such that
# the utopya build system can generate all the plots
build:
  apt_packages:
    - ffmpeg
