# utopya project configuration
# ============================
# pytest-cov / coverage.py ....................................................
# Configuration for pytest-cov coverage reports
# For syntax, see here: https://coverage.readthedocs.io/en/latest/config.html

[tool.coverage.run]
# For a cobertura-compatible coverage report (relevant for CI), need relative
# file paths (and omit some files, see report section)
relative_files = true


[tool.coverage.report]
# Increase precision (from default 0) to be able to discern changes
precision = 2

# Sort by number of lines that are _not_ covered
sort = "Miss"

# Omit files that should not be part of the report
omit = [
    "tests/*",
    "doc/*",
    "setup.py",
]

# isort configuration .........................................................
[tool.isort]
known_first_party = ["utopya", "dantro", "paramspace"]
known_third_party = [
    "dask", "dill", "h5py", "matplotlib", "networkx", "numpy",
    "pkg_resources", "pytest", "ruamel", "scipy", "setuptools", "sympy",
    "xarray",
]

# The following makes the effect of isort compatible to black
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79


# Black configuration .........................................................
[tool.black]
line-length = 79
target-version = ["py38"]

# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.
exclude = '''
/(
    \.eggs
  | \.git
  | \.tox
  | \.venv
  | _build
  | dist
)/
'''
