# Project information file for the utopya demo project
#
# NOTE Any changes to this file need to be registered using the
#      utopya CLI:
#
#         utopya projects register BASE_DIR --info-file path/to/this/file
#
---
project_name: utopyaDemoProject


paths:
  # Path to a directory where the model implementations can be found
  models_dir: models

  # Path to directories where model-specific plots and tests are implemented
  py_plots_dir: model_plots
  py_tests_dir: model_tests

  # Path to project-level default configurations
  mv_project_cfg: cfg/multiverse_base_cfg.yml
  project_base_plots: cfg/project_base_plots.yml


metadata:
  description: A demo project to demonstrate utopya project registration
  authors:
    - utopya developers
  license: LGPLv3+
  language: python3
